language: python
python:
  - "3.9"
  - "nightly"
before_install:
 - python -m pip install --upgrade pip wheel
install:
  - pip install pytest
  - pip install wheel
  - pip install -r requirements.txt
script: python -m pytest tests/