dist: xenial

language: python

cache: pip

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "nightly"

matrix:
    allow_failures:
        - python: "nightly"

before_install:
  - sudo apt-get update
  - sudo apt-get install python3-pip
  - sudo apt-get install python3-pytest
  - python -m pip install --upgrade pip wheel

install:
  - pip install -r requirements.txt

script: python -m pytest tests/
